// Pre-built, back-tested EA strategy templates users can one-click deploy.
// Metrics are illustrative paper-trading baselines from internal back-tests.
export type EATemplate = {
  id: string;
  name: string;
  strategy: string;
  symbol: string;
  lot_size: number;
  description: string;
  timeframe: string;
  tags: string[];
  metrics: { winRate: number; profitFactor: number; sharpe: number; maxDD: number };
  risk: 'Low' | 'Medium' | 'High';
  category: 'Forex' | 'Stocks' | 'Options';
  holdingTime: string;
  target: string;
};

export const EA_TEMPLATES: EATemplate[] = [
  {
    id: 'aurum-smc',
    name: 'Aurum SMC v3.2',
    strategy: 'SMC + ICT',
    symbol: 'XAUUSD',
    lot_size: 0.1,
    timeframe: 'M15',
    description: 'Smart Money Concepts with ICT order-block entries on Gold. Liquidity sweeps + FVG confirmation.',
    tags: ['Gold', 'SMC', 'Swing'],
    metrics: { winRate: 68, profitFactor: 2.1, sharpe: 1.8, maxDD: 8.4 },
    risk: 'Medium',
    category: 'Forex',
    holdingTime: '2-8 hours',
    target: '+1.2% per trade',
  },
  {
    id: 'trend-rider',
    name: 'Trend Rider EMA',
    strategy: 'Trend Following',
    symbol: 'EURUSD',
    lot_size: 0.1,
    timeframe: 'H1',
    description: 'EMA 20/50 crossover with ATR-based trailing stop. Catches sustained directional moves.',
    tags: ['Forex', 'Trend', 'EMA'],
    metrics: { winRate: 54, profitFactor: 1.6, sharpe: 1.4, maxDD: 11.2 },
    risk: 'Low',
    category: 'Forex',
    holdingTime: '6-24 hours',
    target: '+0.8% per trade',
  },
  {
    id: 'london-breakout',
    name: 'London Breakout Pro',
    strategy: 'Breakout',
    symbol: 'GBPJPY',
    lot_size: 0.1,
    timeframe: 'M5',
    description: 'Trades range break of the Asian session at London open with volatility filter.',
    tags: ['Session', 'Breakout'],
    metrics: { winRate: 61, profitFactor: 1.9, sharpe: 1.6, maxDD: 9.7 },
    risk: 'Medium',
    category: 'Forex',
    holdingTime: '1-4 hours',
    target: '+0.6% per trade',
  },
  {
    id: 'mean-rev-bb',
    name: 'Bollinger Mean Reverter',
    strategy: 'Mean Reversion',
    symbol: 'USDJPY',
    lot_size: 0.1,
    timeframe: 'M30',
    description: 'Bollinger 2σ + RSI(14) divergence. Fades extremes inside ranging markets.',
    tags: ['Range', 'Reversal'],
    metrics: { winRate: 72, profitFactor: 1.7, sharpe: 1.5, maxDD: 7.1 },
    risk: 'Low',
    category: 'Forex',
    holdingTime: '3-12 hours',
    target: '+0.5% per trade',
  },
  {
    id: 'tick-scalper',
    name: 'NASDAQ Tick Scalper',
    strategy: 'Scalping',
    symbol: 'US100',
    lot_size: 0.05,
    timeframe: 'M1',
    description: 'Microstructure mean reversion on US100 futures. Tight stops, high frequency.',
    tags: ['Indices', 'Scalp', 'HFT'],
    metrics: { winRate: 78, profitFactor: 1.4, sharpe: 2.1, maxDD: 5.8 },
    risk: 'High',
    category: 'Forex',
    holdingTime: '30s-5 min',
    target: '+0.15% per trade',
  },
  {
    id: 'grid-safe',
    name: 'Safe Grid Hedger',
    strategy: 'Grid',
    symbol: 'AUDUSD',
    lot_size: 0.05,
    timeframe: 'M15',
    description: 'Hedged grid with capped exposure and drawdown lock. Conservative martingale.',
    tags: ['Grid', 'Hedge'],
    metrics: { winRate: 81, profitFactor: 1.3, sharpe: 1.1, maxDD: 14.5 },
    risk: 'High',
    category: 'Forex',
    holdingTime: '1-3 days',
    target: '+2% per cycle',
  },
  // ====== STOCKS ======
  {
    id: 'nifty-momentum',
    name: 'Nifty50 Momentum Rider',
    strategy: 'Momentum',
    symbol: 'NIFTY50',
    lot_size: 1,
    timeframe: '15m',
    description: 'Buys top-5 RSI-strong Nifty50 names at open, exits on VWAP loss or 3:15 PM IST.',
    tags: ['NSE', 'Intraday', 'Momentum'],
    metrics: { winRate: 64, profitFactor: 1.8, sharpe: 1.7, maxDD: 9.2 },
    risk: 'Medium',
    category: 'Stocks',
    holdingTime: 'Intraday · close by 3:15 PM',
    target: '+1% per trade',
  },
  {
    id: 'swing-breakout-200',
    name: 'Swing Breakout 52W',
    strategy: 'Breakout',
    symbol: 'NSE:MULTI',
    lot_size: 1,
    timeframe: '1D',
    description: 'Buys stocks breaking 52-week highs on >2x avg volume. Trailing 10% stop.',
    tags: ['Swing', 'Breakout', 'Equity'],
    metrics: { winRate: 58, profitFactor: 2.4, sharpe: 1.9, maxDD: 12.1 },
    risk: 'Medium',
    category: 'Stocks',
    holdingTime: '5-30 days',
    target: '+8% per trade',
  },
  {
    id: 'dividend-compounder',
    name: 'Dividend Compounder',
    strategy: 'Value + Dividend',
    symbol: 'NSE:BLUECHIP',
    lot_size: 1,
    timeframe: '1W',
    description: 'Long-only basket of high-quality dividend payers, rebalanced quarterly.',
    tags: ['LongTerm', 'Dividend', 'Bluechip'],
    metrics: { winRate: 74, profitFactor: 2.2, sharpe: 1.5, maxDD: 14.0 },
    risk: 'Low',
    category: 'Stocks',
    holdingTime: '3-12 months',
    target: '+18% per year',
  },
  {
    id: 'sp500-gap-fill',
    name: 'S&P Gap Fill Reverter',
    strategy: 'Mean Reversion',
    symbol: 'SPX:MULTI',
    lot_size: 1,
    timeframe: '5m',
    description: 'Fades opening gaps >1% on S&P 500 names, exits on gap fill or end of day.',
    tags: ['US', 'Intraday', 'Reversal'],
    metrics: { winRate: 69, profitFactor: 1.6, sharpe: 1.6, maxDD: 8.5 },
    risk: 'Medium',
    category: 'Stocks',
    holdingTime: 'Intraday',
    target: '+0.7% per trade',
  },
  // ====== OPTIONS ======
  {
    id: 'iron-condor-weekly',
    name: 'Weekly Iron Condor',
    strategy: 'Iron Condor',
    symbol: 'NIFTY',
    lot_size: 1,
    timeframe: 'Weekly',
    description: 'Sells 1-SD weekly iron condor on Nifty every Monday. Manages at 50% profit or 200% loss.',
    tags: ['Options', 'Income', 'Neutral'],
    metrics: { winRate: 82, profitFactor: 1.5, sharpe: 1.4, maxDD: 11.0 },
    risk: 'Medium',
    category: 'Options',
    holdingTime: '3-5 days',
    target: '+3% per week',
  },
  {
    id: 'covered-call-engine',
    name: 'Covered Call Income',
    strategy: 'Covered Call',
    symbol: 'BANKNIFTY',
    lot_size: 1,
    timeframe: 'Monthly',
    description: 'Sells 0.30-delta monthly calls against existing long holdings. Rolls at 21 DTE.',
    tags: ['Options', 'Income', 'Yield'],
    metrics: { winRate: 86, profitFactor: 1.7, sharpe: 1.6, maxDD: 6.4 },
    risk: 'Low',
    category: 'Options',
    holdingTime: '21-30 days',
    target: '+1.5% per month',
  },
  {
    id: 'straddle-event',
    name: 'Event Straddle Sniper',
    strategy: 'Long Straddle',
    symbol: 'NIFTY',
    lot_size: 1,
    timeframe: 'Event',
    description: 'Buys ATM straddles 2 days before RBI/Fed/earnings, exits at IV crush or +50%.',
    tags: ['Options', 'Volatility', 'Event'],
    metrics: { winRate: 48, profitFactor: 2.6, sharpe: 1.8, maxDD: 16.0 },
    risk: 'High',
    category: 'Options',
    holdingTime: '1-3 days',
    target: '+25% per event',
  },
  {
    id: 'put-credit-spread',
    name: 'Bullish Put Credit Spread',
    strategy: 'Put Credit Spread',
    symbol: 'SPY',
    lot_size: 1,
    timeframe: 'Weekly',
    description: 'Sells 0.20-delta put spreads on SPY in confirmed uptrend. Exits at 50% profit.',
    tags: ['Options', 'Bullish', 'Income'],
    metrics: { winRate: 79, profitFactor: 1.6, sharpe: 1.7, maxDD: 9.8 },
    risk: 'Medium',
    category: 'Options',
    holdingTime: '5-10 days',
    target: '+2% per trade',
  },
];