import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useRealtimeSignals } from '@/hooks/useRealtime';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { toast } from 'sonner';
import { Loader2, Radar, Bookmark, Zap, Gauge, Landmark, Brain, Sparkles } from 'lucide-react';
import {
  fetchPrice, fetchCandleData, computeRSI, computeATR, getCurrencySymbol,
  WATCHLIST_NSE_MAIN, WATCHLIST_NSE_TECH, WATCHLIST_US_TECH, WATCHLIST_US_FINANCE, WATCHLIST_CANADA_TSX, WATCHLIST_UK_LSE, WATCHLIST_GLOBAL_ETFS,
  BreakoutSignal, ScalpScore, BigMoneySignal, SmartMoneySignal,
} from '@/lib/marketData';
import { EXCHANGES, getExchangeForSymbol } from '@/lib/marketHours';

interface DbScanRow {
  id: string;
  symbol: string;
  category: 'breakout' | 'scalp' | 'big_money' | 'smart_money';
  price: number;
  change_percent: number;
  metrics: BreakoutSignal | ScalpScore | BigMoneySignal | SmartMoneySignal;
  computed_at: string;
}

interface AiSignalRow {
  symbol: string;
  category: 'breakout' | 'scalp' | 'big_money' | 'smart_money' | 'manual';
  signal: 'BUY' | 'SELL' | 'HOLD';
  confidence: number;
  rationale: string;
  risks: string[];
  price: number;
  model: string;
  computed_at: string;
}

interface ScanResult {
  symbol: string;
  price: number;
  changePct: number;
  volume: number;
  rsi14: number;
  atrPct: number;
  signal: 'BUY' | 'SELL' | 'HOLD';
  currency: string;
}

const signalTypeColor: Record<string, string> = {
  BUY: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  SELL: 'bg-red-500/20 text-red-400 border-red-500/30',
  STRONG_BUY: 'bg-emerald-500/30 text-emerald-300 border-emerald-400/50',
  STRONG_SELL: 'bg-red-500/30 text-red-300 border-red-400/50',
  HOLD: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
};

const Scanner = () => {
  const { user } = useAuth();
  const { signals } = useRealtimeSignals(user?.id);
  const [watchlist, setWatchlist] = useState('NSE_MAIN');
  const [results, setResults] = useState<ScanResult[]>([]);
  const [scanning, setScanning] = useState(false);
  const [lastScanned, setLastScanned] = useState<Date | null>(null);
  const [scanTime, setScanTime] = useState(0);
  const [customSymbols, setCustomSymbols] = useState(() => {
    try { return JSON.parse(localStorage.getItem('scanner_custom_symbols') || '[]') as string[]; } catch { return []; }
  });
  const [newSymbol, setNewSymbol] = useState('');
  const [userWatchlists, setUserWatchlists] = useState<any[]>([]);
  const [showSaveWl, setShowSaveWl] = useState(false);
  const [saveWlName, setSaveWlName] = useState('');

  // Strategy Scan results are computed server-side on a schedule (pg_cron ->
  // strategy-scanner edge function, every 15min during market hours) and
  // just read here — the page never runs the scan itself. "Refresh now"
  // triggers an out-of-schedule run when someone wants fresher data
  // immediately.
  const [dbScanRows, setDbScanRows] = useState<DbScanRow[]>([]);
  const [loadingScanRows, setLoadingScanRows] = useState(true);
  const [triggeringScan, setTriggeringScan] = useState(false);
  const [universeSize, setUniverseSize] = useState<number | null>(null);

  // AI-authored signals (Claude, via the user's own connected Anthropic key
  // in Settings) generated by the same background scan, keyed by
  // "symbol|category" so each strategy tab can show its own AI call.
  const [aiSignals, setAiSignals] = useState<Record<string, AiSignalRow>>({});
  const [aiDetail, setAiDetail] = useState<AiSignalRow | null>(null);

  const loadStrategyResults = async () => {
    setLoadingScanRows(true);
    const [{ data, error }, { data: aiData }] = await Promise.all([
      supabase.from('strategy_scan_results').select('*').order('computed_at', { ascending: false }),
      supabase.from('ai_signals').select('*'),
    ]);
    if (error) toast.error('Failed to load scan results: ' + error.message);
    setDbScanRows((data as DbScanRow[]) || []);
    const aiMap: Record<string, AiSignalRow> = {};
    for (const row of (aiData as AiSignalRow[]) || []) aiMap[`${row.symbol}|${row.category}`] = row;
    setAiSignals(aiMap);
    setLoadingScanRows(false);
  };

  useEffect(() => {
    loadStrategyResults();
    supabase.from('nse_universe').select('*', { count: 'exact', head: true }).then(({ count }) => setUniverseSize(count ?? null));
  }, []);

  const triggerManualScan = async () => {
    setTriggeringScan(true);
    const { error } = await supabase.functions.invoke('strategy-scanner');
    if (error) toast.error('Scan failed: ' + error.message);
    else toast.success('Scan complete');
    await loadStrategyResults();
    setTriggeringScan(false);
  };

  const strategyLastScanned = dbScanRows[0]?.computed_at ? new Date(dbScanRows[0].computed_at) : null;
  const byCategory = (cat: DbScanRow['category']) => dbScanRows.filter(r => r.category === cat);
  const breakoutResults = byCategory('breakout').sort((a, b) => (b.metrics as BreakoutSignal).volumeRatio - (a.metrics as BreakoutSignal).volumeRatio);
  const scalpResults = byCategory('scalp').sort((a, b) => (b.metrics as ScalpScore).score - (a.metrics as ScalpScore).score).slice(0, 15);
  const bigMoneyResults = byCategory('big_money').sort((a, b) => (b.metrics as BigMoneySignal).turnoverRatio - (a.metrics as BigMoneySignal).turnoverRatio);
  const smartMoneyResults = byCategory('smart_money').sort((a, b) => (b.metrics as SmartMoneySignal).volumeRatio - (a.metrics as SmartMoneySignal).volumeRatio);

  useEffect(() => {
    if (!user) return;
    supabase.from('watchlists').select('*').eq('user_id', user.id).order('created_at').then(({ data }) => {
      setUserWatchlists(data || []);
    });
  }, [user]);

  const getSymbols = () => {
    if (watchlist === 'NSE_MAIN') return WATCHLIST_NSE_MAIN;
    if (watchlist === 'NSE_TECH') return WATCHLIST_NSE_TECH;
    if (watchlist === 'US_TECH') return WATCHLIST_US_TECH;
    if (watchlist === 'US_FINANCE') return WATCHLIST_US_FINANCE;
    if (watchlist === 'CANADA_TSX') return WATCHLIST_CANADA_TSX;
    if (watchlist === 'UK_LSE') return WATCHLIST_UK_LSE;
    if (watchlist === 'GLOBAL_ETFS') return WATCHLIST_GLOBAL_ETFS;
    if (watchlist === 'CUSTOM') return customSymbols;
    const wl = userWatchlists.find(w => w.id === watchlist);
    if (wl) return [];
    return customSymbols;
  };

  const scanUserWatchlist = async (wlId: string) => {
    const { data } = await supabase.from('watchlist_symbols').select('symbol').eq('watchlist_id', wlId).eq('user_id', user!.id);
    return data?.map((d: any) => d.symbol) || [];
  };

  const scan = async () => {
    let symbols = getSymbols();
    // If user watchlist selected, fetch symbols first
    if (watchlist !== 'NSE_MAIN' && watchlist !== 'NSE_TECH' && watchlist !== 'CUSTOM') {
      symbols = await scanUserWatchlist(watchlist);
    }
    if (symbols.length === 0) { toast.error('No symbols to scan'); return; }
    setScanning(true);
    const start = Date.now();
    const scanned: ScanResult[] = [];

    for (const sym of symbols) {
      try {
        const [data, candles] = await Promise.all([
          fetchPrice(sym),
          fetchCandleData(sym, '1d', '3mo'),
        ]);
        const rsiSeries = computeRSI(candles, 14);
        const atrSeries = computeATR(candles, 14);
        const rsi14 = rsiSeries[rsiSeries.length - 1] ?? 50;
        const lastAtr = atrSeries[atrSeries.length - 1];
        const atrPct = lastAtr !== null && data.price ? (lastAtr / data.price) * 100 : 0;
        const signal: 'BUY' | 'SELL' | 'HOLD' = rsi14 < 35 ? 'BUY' : rsi14 > 65 ? 'SELL' : 'HOLD';
        scanned.push({ symbol: sym, price: data.price, changePct: data.changePercent, volume: data.volume, rsi14, atrPct, signal, currency: getCurrencySymbol(sym) });
      } catch { /* skip */ }
    }
    setResults(scanned);
    setLastScanned(new Date());
    setScanTime((Date.now() - start) / 1000);
    setScanning(false);
  };

  const generateSignal = async (r: ScanResult) => {
    if (!user) return;
    await supabase.from('signals').insert({ user_id: user.id, symbol: r.symbol, signal_type: r.signal, price: r.price });
    toast.success(`Signal generated: ${r.signal} ${r.symbol}`);
  };

  const addCustomSymbol = () => {
    if (!newSymbol.trim()) return;
    const updated = [...customSymbols, newSymbol.toUpperCase()];
    setCustomSymbols(updated);
    localStorage.setItem('scanner_custom_symbols', JSON.stringify(updated));
    setNewSymbol('');
  };

  const removeCustomSymbol = (sym: string) => {
    const updated = customSymbols.filter(s => s !== sym);
    setCustomSymbols(updated);
    localStorage.setItem('scanner_custom_symbols', JSON.stringify(updated));
  };

  const saveAsWatchlist = async () => {
    if (!saveWlName.trim() || !user || results.length === 0) return;
    const { data: wl } = await supabase.from('watchlists').insert({ user_id: user.id, name: saveWlName.trim(), color: '#f59e0b', is_default: false } as any).select().single();
    if (!wl) { toast.error('Failed to create watchlist'); return; }
    await supabase.from('watchlist_symbols').insert(results.map(r => ({ watchlist_id: wl.id, user_id: user.id, symbol: r.symbol })) as any);
    toast.success(`Watchlist "${saveWlName}" created with ${results.length} symbols`);
    setShowSaveWl(false); setSaveWlName('');
  };

  const signalColor: Record<string, string> = { BUY: 'bg-emerald-500/20 text-emerald-400', SELL: 'bg-red-500/20 text-red-400', HOLD: 'bg-yellow-500/20 text-yellow-400' };

  const AiCallCell = ({ symbol, category }: { symbol: string; category: string }) => {
    const ai = aiSignals[`${symbol}|${category}`];
    if (!ai) return <span className="text-xs text-muted-foreground">—</span>;
    return (
      <button
        onClick={() => setAiDetail(ai)}
        className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs border hover:opacity-80 ${signalTypeColor[ai.signal]}`}
      >
        <Sparkles className="h-3 w-3" /> {ai.signal} {ai.confidence}%
      </button>
    );
  };

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold flex items-center gap-2"><Radar className="h-6 w-6 text-primary" /> Scanner</h1>

      <Tabs defaultValue="scan">
        <TabsList>
          <TabsTrigger value="scan">Live Scan</TabsTrigger>
          <TabsTrigger value="strategy">Strategy Scan</TabsTrigger>
          <TabsTrigger value="signals">
            Saved Signals
            {signals.length > 0 && <span className="ml-2 bg-primary/20 text-primary text-xs rounded-full px-1.5">{signals.length}</span>}
          </TabsTrigger>
        </TabsList>

        <TabsContent value="scan" className="space-y-6">
      <Card className="card-glow">
        <CardContent className="pt-6">
          <div className="flex flex-wrap gap-4 items-end">
            <div>
              <label className="text-xs text-muted-foreground block mb-1">Watchlist</label>
              <Select value={watchlist} onValueChange={setWatchlist}>
                <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="NSE_MAIN">🇮🇳 NSE Main</SelectItem>
                  <SelectItem value="NSE_TECH">🇮🇳 NSE Tech</SelectItem>
                  <SelectItem value="US_TECH">🇺🇸 US Tech</SelectItem>
                  <SelectItem value="US_FINANCE">🇺🇸 US Finance</SelectItem>
                  <SelectItem value="CANADA_TSX">🇨🇦 TSX Canada</SelectItem>
                  <SelectItem value="UK_LSE">🇬🇧 LSE London</SelectItem>
                  <SelectItem value="GLOBAL_ETFS">🌍 Global ETFs</SelectItem>
                  <SelectItem value="CUSTOM">Custom</SelectItem>
                  {userWatchlists.map((wl: any) => <SelectItem key={wl.id} value={wl.id}>📌 {wl.name}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <Button onClick={scan} disabled={scanning}>
              {scanning ? <><Loader2 className="h-4 w-4 animate-spin mr-2" /> Scanning...</> : 'Scan Now'}
            </Button>
            {lastScanned && <span className="text-xs text-muted-foreground">Last: {lastScanned.toLocaleTimeString()} • Scanned {results.length} symbols in {scanTime.toFixed(1)}s</span>}
          </div>
        </CardContent>
      </Card>

      {watchlist === 'CUSTOM' && (
        <Card className="card-glow">
          <CardHeader><CardTitle className="text-sm">Custom Symbols</CardTitle></CardHeader>
          <CardContent>
            <div className="flex gap-2 mb-3">
              <Input placeholder="e.g. TCS.NS" value={newSymbol} onChange={e => setNewSymbol(e.target.value)} className="w-40" onKeyDown={e => e.key === 'Enter' && addCustomSymbol()} />
              <Button size="sm" onClick={addCustomSymbol}>Add</Button>
            </div>
            <div className="flex gap-2 flex-wrap">
              {customSymbols.map(s => (
                <Badge key={s} variant="outline" className="cursor-pointer" onClick={() => removeCustomSymbol(s)}>{s} ×</Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {results.length > 0 && (
        <Card className="card-glow">
          <CardContent className="pt-6">
            <div className="table-striped overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Symbol</TableHead><TableHead>Price</TableHead><TableHead>Change%</TableHead>
                    <TableHead>Volume</TableHead><TableHead>RSI14</TableHead><TableHead>ATR%</TableHead>
                    <TableHead>Signal</TableHead><TableHead>Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {results.map(r => (
                    <TableRow key={r.symbol}>
                      <TableCell className="font-mono font-semibold">
                        <span className="mr-1">{EXCHANGES[getExchangeForSymbol(r.symbol)]?.flag || '🌐'}</span>
                        {r.symbol}
                        <span className="text-[10px] text-muted-foreground ml-1">{getExchangeForSymbol(r.symbol)}</span>
                      </TableCell>
                      <TableCell className="font-mono">{r.currency}{r.price.toFixed(2)}</TableCell>
                      <TableCell className={`font-mono ${r.changePct >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{r.changePct >= 0 ? '+' : ''}{r.changePct.toFixed(2)}%</TableCell>
                      <TableCell className="font-mono text-xs">{(r.volume / 1000000).toFixed(1)}M</TableCell>
                      <TableCell className="font-mono">{r.rsi14.toFixed(1)}</TableCell>
                      <TableCell className="font-mono">{r.atrPct.toFixed(2)}%</TableCell>
                      <TableCell><span className={`px-2 py-0.5 rounded text-xs ${signalColor[r.signal]}`}>{r.signal}</span></TableCell>
                      <TableCell>
                        <div className="flex gap-1">
                          <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => generateSignal(r)}>Signal</Button>
                          <Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => window.location.href = `/trade?symbol=${r.symbol}`}>Trade</Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      )}

      {results.length > 0 && (
        <Button variant="outline" onClick={() => setShowSaveWl(true)}>
          <Bookmark className="h-4 w-4 mr-2" /> Save scan results as new watchlist
        </Button>
      )}
        </TabsContent>

        <TabsContent value="strategy" className="space-y-6">
          <Card className="card-glow">
            <CardContent className="pt-6">
              <div className="flex flex-wrap gap-4 items-center">
                <Button variant="outline" onClick={triggerManualScan} disabled={triggeringScan}>
                  {triggeringScan ? <><Loader2 className="h-4 w-4 animate-spin mr-2" /> Refreshing...</> : 'Refresh now'}
                </Button>
                {loadingScanRows ? (
                  <span className="text-xs text-muted-foreground flex items-center gap-1"><Loader2 className="h-3 w-3 animate-spin" /> Loading...</span>
                ) : strategyLastScanned ? (
                  <span className="text-xs text-muted-foreground">
                    Background scan last ran: {strategyLastScanned.toLocaleTimeString()} ({strategyLastScanned.toLocaleDateString()})
                  </span>
                ) : (
                  <span className="text-xs text-muted-foreground">No background scan has run yet — click Refresh now.</span>
                )}
              </div>
              <p className="text-[10px] text-muted-foreground mt-3">
                Rotates through {universeSize ? universeSize.toLocaleString('en-IN') : 'the full'} NSE-listed equities in the background automatically, ~400 at a time every 15 minutes during market hours (8:30am-3:30pm IST, Mon-Fri) — the full universe cycles roughly every 1.5-2 hours, so results across different stocks may be a few chunks apart in freshness. This page just displays the latest results, no need to trigger it yourself. Standard technical-analysis heuristics computed from real price/volume history — not signals from a paid data provider, not financial advice. See each tab's description for the exact rule.
                {' '}The "AI Call" column shows a genuine Claude-reasoned BUY/SELL/HOLD for every match, written by the background scan when an Anthropic key is connected in Settings — click it for the full rationale and risks. Shows "—" until AI is connected there.
              </p>
            </CardContent>
          </Card>

          {dbScanRows.length === 0 && !loadingScanRows ? (
            <div className="text-center text-muted-foreground py-12">No results yet — click "Refresh now" to run the first scan.</div>
          ) : (
            <Tabs defaultValue="breakout">
              <TabsList>
                <TabsTrigger value="breakout"><Zap className="h-3.5 w-3.5 mr-1" /> Breakout ({breakoutResults.length})</TabsTrigger>
                <TabsTrigger value="scalp"><Gauge className="h-3.5 w-3.5 mr-1" /> Scalping ({scalpResults.length})</TabsTrigger>
                <TabsTrigger value="bigmoney"><Landmark className="h-3.5 w-3.5 mr-1" /> Big Money ({bigMoneyResults.length})</TabsTrigger>
                <TabsTrigger value="smartmoney"><Brain className="h-3.5 w-3.5 mr-1" /> Smart Money ({smartMoneyResults.length})</TabsTrigger>
              </TabsList>

              <TabsContent value="breakout">
                <Card className="card-glow">
                  <CardHeader className="pb-2"><CardTitle className="text-sm">Breakout: close above the prior 20-session high on above-average volume</CardTitle></CardHeader>
                  <CardContent>
                    {breakoutResults.length === 0 ? <p className="text-sm text-muted-foreground py-8 text-center">No breakouts found in this scan.</p> : (
                      <Table>
                        <TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead>Price</TableHead><TableHead>Change%</TableHead><TableHead>20D Resistance</TableHead><TableHead>% Above</TableHead><TableHead>Vol Ratio</TableHead><TableHead>AI Call</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader>
                        <TableBody>
                          {breakoutResults.map(r => {
                            const m = r.metrics as BreakoutSignal;
                            const cur = getCurrencySymbol(r.symbol);
                            return (
                              <TableRow key={r.symbol}>
                                <TableCell className="font-mono font-semibold">{r.symbol}</TableCell>
                                <TableCell className="font-mono">{cur}{r.price.toFixed(2)}</TableCell>
                                <TableCell className={`font-mono ${r.change_percent >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{r.change_percent >= 0 ? '+' : ''}{r.change_percent.toFixed(2)}%</TableCell>
                                <TableCell className="font-mono text-xs">{cur}{m.resistance20.toFixed(2)}</TableCell>
                                <TableCell className="font-mono text-emerald-400">+{m.pctAboveResistance.toFixed(2)}%</TableCell>
                                <TableCell className="font-mono">{m.volumeRatio.toFixed(1)}x</TableCell>
                                <TableCell><AiCallCell symbol={r.symbol} category="breakout" /></TableCell>
                                <TableCell className="text-right"><Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => window.location.href = `/stock-profile?symbol=${r.symbol}`}>View</Button></TableCell>
                              </TableRow>
                            );
                          })}
                        </TableBody>
                      </Table>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="scalp">
                <Card className="card-glow">
                  <CardHeader className="pb-2"><CardTitle className="text-sm">Scalping suitability: high liquidity (turnover) + high volatility (ATR%) right now — top 15</CardTitle></CardHeader>
                  <CardContent>
                    {scalpResults.length === 0 ? <p className="text-sm text-muted-foreground py-8 text-center">No candidates found in this scan.</p> : (
                      <Table>
                        <TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead>Price</TableHead><TableHead>ATR%</TableHead><TableHead>Avg Turnover</TableHead><TableHead>Score</TableHead><TableHead>AI Call</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader>
                        <TableBody>
                          {scalpResults.map(r => {
                            const m = r.metrics as ScalpScore;
                            return (
                              <TableRow key={r.symbol}>
                                <TableCell className="font-mono font-semibold">{r.symbol}</TableCell>
                                <TableCell className="font-mono">{getCurrencySymbol(r.symbol)}{r.price.toFixed(2)}</TableCell>
                                <TableCell className="font-mono">{m.atrPct.toFixed(2)}%</TableCell>
                                <TableCell className="font-mono text-xs">₹{m.avgTurnoverCr.toFixed(1)}Cr</TableCell>
                                <TableCell><Badge variant="outline" className={m.score >= 70 ? 'text-emerald-400 border-emerald-400/30' : m.score >= 40 ? 'text-yellow-400 border-yellow-400/30' : 'text-muted-foreground'}>{m.score}</Badge></TableCell>
                                <TableCell><AiCallCell symbol={r.symbol} category="scalp" /></TableCell>
                                <TableCell className="text-right"><Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => window.location.href = `/stock-profile?symbol=${r.symbol}`}>View</Button></TableCell>
                              </TableRow>
                            );
                          })}
                        </TableBody>
                      </Table>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="bigmoney">
                <Card className="card-glow">
                  <CardHeader className="pb-2"><CardTitle className="text-sm">Big Money: today's turnover (price × volume) is 1.5x+ this stock's own recent average</CardTitle></CardHeader>
                  <CardContent>
                    {bigMoneyResults.length === 0 ? <p className="text-sm text-muted-foreground py-8 text-center">No unusual turnover found in this scan.</p> : (
                      <Table>
                        <TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead>Price</TableHead><TableHead>Change%</TableHead><TableHead>Turnover Today</TableHead><TableHead>Avg Turnover</TableHead><TableHead>Ratio</TableHead><TableHead>AI Call</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader>
                        <TableBody>
                          {bigMoneyResults.map(r => {
                            const m = r.metrics as BigMoneySignal;
                            return (
                              <TableRow key={r.symbol}>
                                <TableCell className="font-mono font-semibold">{r.symbol}</TableCell>
                                <TableCell className="font-mono">{getCurrencySymbol(r.symbol)}{r.price.toFixed(2)}</TableCell>
                                <TableCell className={`font-mono ${r.change_percent >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{r.change_percent >= 0 ? '+' : ''}{r.change_percent.toFixed(2)}%</TableCell>
                                <TableCell className="font-mono text-xs">₹{m.turnoverTodayCr.toFixed(1)}Cr</TableCell>
                                <TableCell className="font-mono text-xs">₹{m.avgTurnoverCr.toFixed(1)}Cr</TableCell>
                                <TableCell className="font-mono text-primary">{m.turnoverRatio.toFixed(1)}x</TableCell>
                                <TableCell><AiCallCell symbol={r.symbol} category="big_money" /></TableCell>
                                <TableCell className="text-right"><Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => window.location.href = `/stock-profile?symbol=${r.symbol}`}>View</Button></TableCell>
                              </TableRow>
                            );
                          })}
                        </TableBody>
                      </Table>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="smartmoney">
                <Card className="card-glow">
                  <CardHeader className="pb-2"><CardTitle className="text-sm">Smart Money: volume 1.4x+ average alongside a 1%+ same-day move (accumulation/distribution footprint)</CardTitle></CardHeader>
                  <CardContent>
                    {smartMoneyResults.length === 0 ? <p className="text-sm text-muted-foreground py-8 text-center">No footprints found in this scan.</p> : (
                      <Table>
                        <TableHeader><TableRow><TableHead>Symbol</TableHead><TableHead>Price</TableHead><TableHead>Change%</TableHead><TableHead>Vol Ratio</TableHead><TableHead>Direction</TableHead><TableHead>AI Call</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader>
                        <TableBody>
                          {smartMoneyResults.map(r => {
                            const m = r.metrics as SmartMoneySignal;
                            return (
                              <TableRow key={r.symbol}>
                                <TableCell className="font-mono font-semibold">{r.symbol}</TableCell>
                                <TableCell className="font-mono">{getCurrencySymbol(r.symbol)}{r.price.toFixed(2)}</TableCell>
                                <TableCell className={`font-mono ${r.change_percent >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{r.change_percent >= 0 ? '+' : ''}{r.change_percent.toFixed(2)}%</TableCell>
                                <TableCell className="font-mono">{m.volumeRatio.toFixed(1)}x</TableCell>
                                <TableCell><Badge variant="outline" className={m.direction === 'Accumulation' ? 'text-emerald-400 border-emerald-400/30' : 'text-red-400 border-red-400/30'}>{m.direction}</Badge></TableCell>
                                <TableCell><AiCallCell symbol={r.symbol} category="smart_money" /></TableCell>
                                <TableCell className="text-right"><Button size="sm" variant="outline" className="h-7 text-xs" onClick={() => window.location.href = `/stock-profile?symbol=${r.symbol}`}>View</Button></TableCell>
                              </TableRow>
                            );
                          })}
                        </TableBody>
                      </Table>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>
            </Tabs>
          )}
        </TabsContent>

        <TabsContent value="signals">
          <Card className="card-glow">
            <CardHeader><CardTitle>Saved Signals (Real-time · last 50)</CardTitle></CardHeader>
            <CardContent>
              {signals.length === 0 ? (
                <div className="text-center text-muted-foreground py-12">No signals yet. Run a scan and click "Signal" to save one.</div>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Symbol</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Price</TableHead>
                      <TableHead>When</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {signals.map(s => (
                      <TableRow key={s.id}>
                        <TableCell className="font-mono font-semibold">{s.symbol}</TableCell>
                        <TableCell>
                          <span className={`px-2 py-0.5 rounded text-xs border ${signalTypeColor[s.signal_type] || signalTypeColor.HOLD}`}>
                            {s.signal_type}
                          </span>
                        </TableCell>
                        <TableCell className="font-mono">₹{Number(s.price).toFixed(2)}</TableCell>
                        <TableCell className="text-xs text-muted-foreground font-mono">
                          {new Date(s.created_at).toLocaleString()}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <Dialog open={showSaveWl} onOpenChange={setShowSaveWl}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader>
            <DialogTitle>Save as Watchlist</DialogTitle>
            <DialogDescription>Create a new watchlist from {results.length} scanned symbols</DialogDescription>
          </DialogHeader>
          <Input placeholder="Watchlist name" value={saveWlName} onChange={e => setSaveWlName(e.target.value)} />
          <DialogFooter>
            <Button onClick={saveAsWatchlist} disabled={!saveWlName.trim()}>Create Watchlist</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!aiDetail} onOpenChange={(open) => !open && setAiDetail(null)}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" /> {aiDetail?.symbol} — AI Call
            </DialogTitle>
            <DialogDescription>
              {aiDetail && <>Reasoned by {aiDetail.model} at {new Date(aiDetail.computed_at).toLocaleString()}, based on real price/volume data — not financial advice.</>}
            </DialogDescription>
          </DialogHeader>
          {aiDetail && (
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <span className={`px-2 py-0.5 rounded text-xs border ${signalTypeColor[aiDetail.signal]}`}>{aiDetail.signal}</span>
                <span className="text-xs text-muted-foreground">Confidence: {aiDetail.confidence}%</span>
                <span className="text-xs text-muted-foreground font-mono ml-auto">₹{Number(aiDetail.price).toFixed(2)}</span>
              </div>
              <p className="text-sm">{aiDetail.rationale}</p>
              {aiDetail.risks?.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-muted-foreground mb-1">Risks</p>
                  <ul className="text-xs text-muted-foreground list-disc pl-4 space-y-0.5">
                    {aiDetail.risks.map((risk, i) => <li key={i}>{risk}</li>)}
                  </ul>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Scanner;
